version: '3.8'
services:
  chroma-db:
    image: chromadb/chroma:latest
    environment:
      CHROMA_SERVER_HOST: 0.0.0.0
      CHROMA_SERVER_HTTP_PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/.chroma/index
      - ./data/documents:/app/data/documents
    restart: unless-stopped
volumes:
  chroma_data:
